version: '3.7'

services: 
  db:
    build: ./docker/postgres
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  keycloak:
    image: quay.io/keycloak/keycloak:10.0.0
    ports: 
      - 9000:8080
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_pass
      DB_SCHEMA: public
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    