version: '3.7'

services: 
  db:
    build: ./docker/postgres
    ports: # Just for dev
      - 5432:5432
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  adminer: # Just for dev
    image: adminer
    restart: always
    ports:
      - 9090:8080
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    