server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/api/v1/menu/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowCredentials: "true"
            allowedMethods:
              - HEAD
              - GET
              - POST
              - PATCH
              - DELETE
            allowedHeaders:
              - "Authorization"
              - "Cache-Control"
              - "Content-Type"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka